"""
Auto-generate a remediation PR from a drift report.

Strategy:
  1. Build a Markdown PR body grouped by category + severity.
  2. For each MODIFIED item with a TF-recoverable attribute, emit a
     remediation `terraform apply` step in a checklist.
  3. If a `gh` CLI is available (and --create flag passed), open the PR
     with the body. Otherwise write the body to disk for the user to file.

Zero deps: shells out to `gh` and `git` only when explicitly requested.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import textwrap
from typing import Iterable

_SEV_ICON = {"CRITICAL": ":red_circle:", "HIGH": ":large_orange_circle:",
             "MEDIUM": ":yellow_circle:", "LOW": ":white_circle:"}


def render_pr_body(findings: list[dict], drift_count: int) -> str:
    if not findings:
        return ("# Terraform drift report\n\n"
                "_No actionable drift detected. Inventories match._\n")

    by_cat: dict[str, list[dict]] = {}
    for f in findings:
        by_cat.setdefault(f.get("category", "other"), []).append(f)

    sev_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}

    lines = [
        "# Terraform drift report",
        "",
        f"**{drift_count}** structural drift items, **{len(findings)}** flagged by rules.",
        "",
        "## Action items",
        "",
    ]

    for cat, items in sorted(by_cat.items()):
        lines.append(f"### {cat.upper()}")
        items.sort(key=lambda f: sev_order.get(f.get("severity", "LOW"), 9))
        for f in items:
            lines.append(
                f"- {_SEV_ICON.get(f.get('severity', '?'), '')} "
                f"**[{f.get('severity', '?')}]** {f.get('title', '')}\n"
                f"  - resource: `{f.get('address', '')}`\n"
                f"  - kind: `{f.get('kind', '')}`\n"
                f"  - detail: {f.get('detail', '')}\n"
                f"  - fix: _{f.get('remediation', '')}_"
            )
        lines.append("")

    lines.extend([
        "## Suggested remediation steps",
        "",
        "```bash",
        "# 1. Inspect what Terraform thinks should be deployed",
        "terraform plan",
        "",
        "# 2. For ADDED items not in IaC: import or remove via console",
        "#    terraform import <resource>.<name> <id>",
        "",
        "# 3. For MODIFIED items: re-apply to overwrite drift",
        "terraform apply",
        "",
        "# 4. For REMOVED items: re-apply to recreate, OR remove from .tf if intentional",
        "```",
        "",
        "_This PR was auto-generated by [terraform-drift-detector](https://github.com/CyberEnthusiastic/terraform-drift-detector)._",
    ])
    return "\n".join(lines) + "\n"


def write_pr_body(findings: list[dict], drift_count: int, path: str) -> str:
    body = render_pr_body(findings, drift_count)
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    return path


def open_pr_via_gh(title: str, body_path: str, branch: str | None = None) -> tuple[bool, str]:
    """
    Try to open a PR via the `gh` CLI. Returns (success, message).
    Caller is responsible for having committed the body file (or any
    remediation tf changes) on a feature branch first.
    """
    if not shutil.which("gh"):
        return False, "gh CLI not found on PATH; install from https://cli.github.com"

    cmd = ["gh", "pr", "create", "--title", title, "--body-file", body_path]
    if branch:
        cmd.extend(["--head", branch])

    try:
        proc = subprocess.run(cmd, check=False, capture_output=True, text=True, timeout=60)
    except subprocess.SubprocessError as exc:
        return False, f"gh invocation failed: {exc}"

    if proc.returncode == 0:
        return True, proc.stdout.strip()
    return False, (proc.stderr or proc.stdout or "gh returned non-zero").strip()
